# Generated by Django 6.0.7 on 2026-07-11 14:13

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameGenres',
            fields=[
                ('pk', models.CompositePrimaryKey('game_id', 'genre_id', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'game_genres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GamePlatforms',
            fields=[
                ('pk', models.CompositePrimaryKey('game_id', 'platform_id', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'game_platforms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('game_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('release_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)])),
                ('developer', models.CharField(blank=True, max_length=150, null=True)),
                ('publisher', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'games',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'genres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Interactions',
            fields=[
                ('interaction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('view', 'Wyświetlenie'), ('click', 'Kliknięcie'), ('like', 'Polubienie'), ('dislike', 'Brak polubienia'), ('favorite', 'Ulubione'), ('watchlist', 'Lista do obejrzenia'), ('watch', 'Obejrzenie'), ('play', 'Uruchomienie gry'), ('skip', 'Pominięcie')], max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'interactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MlModels',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('version', models.CharField(max_length=50)),
                ('algorithm_type', models.CharField(max_length=50)),
                ('metrics_json', models.JSONField(blank=True, null=True)),
                ('trained_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ml_models',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieGenres',
            fields=[
                ('pk', models.CompositePrimaryKey('movie_id', 'genre_id', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'movie_genres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movie_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('release_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1888), django.core.validators.MaxValueValidator(2100)])),
                ('director', models.CharField(blank=True, max_length=150, null=True)),
                ('duration_min', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Platforms',
            fields=[
                ('platform_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'platforms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('rating_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('score', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('rated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'ratings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecommendationItems',
            fields=[
                ('recommendation_item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('predicted_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('position', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'db_table': 'recommendation_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('recommendation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'recommendations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('preferences_json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
