# Generated by Django 6.0.7 on 2026-07-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='tmdb_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
