# Generated by Django 6.0.7 on 2026-07-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_movies_tmdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='poster_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
